version: '3.6'
services:
  database:
    image: postgres:9.6.9
    hostname: postgres
    container_name: simple-riqum-database
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=adminadmin
      - POSTGRES_DB=riqum
    volumes:
      - ./data/db:/var/lib/postgresql/data

  rabbit:
    image: rabbitmq:3-management
    hostname: rabbitmq
    container_name: simple-riqum-rabbitmq
    ports:
      - 9090:15672
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=rabbit
      - RABBITMQ_DEFAULT_PASS=password
      - RABBITMQ_DEFAULT_VHOST=/
    volumes:
      - ./data/rabbits:/var/lib/rabbitmq/mnesia/rabbit@my-rabbit
