FROM node:slim

ENV NODE_ENV=development \
    DATABASE_URL= \
    AMQP_USERNAME=rabbit \
    AMQP_PASSWORD=password \
    DEPLOYMENT_SCRIPTS_DIR=/scripts \
    DEBUG=simple-riqum*

COPY . .
RUN npm install

CMD ["./node_modules/.bin/babel-node", "src/qworker/index.js"]
