FROM google/cloud-sdk:latest

ENV NODE_ENV=development \
    DATABASE_URL= \
    AMQP_USERNAME=rabbit \
    AMQP_PASSWORD=password \
    DEPLOYMENT_SCRIPTS_DIR=/scripts \
    DEBUG=simple-riqum*

RUN curl -sL https://deb.nodesource.com/setup_8.x | bash
RUN apt-get install -y nodejs && echo node -v

COPY . .
RUN npm install

CMD ["./node_modules/.bin/babel-node", "src/qworker/index.js"]
